name: Tycho site-docs
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
on:
  push:
    branches: 
      - 'main'
    paths:
      - 'src/site/**'
  pull_request:
    branches: 
      - 'main'
    paths:
      - 'src/site/**'
      - .github/workflows/sitedocs.yml

permissions:
  contents: read

jobs:
  build:
    name: Build site-docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write
      repository-projects: write
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@6f7a8d2348e2a4aa5defafcdaafe5aef3f83bd4b # v5.4.0
    - name: Checkout tycho code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
       path: 'tycho'
    - name: Checkout page
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
       path: 'page'
       token: ${{ secrets.TYCHO_SITE_PAT }}
       repository: 'eclipse-tycho/eclipse-tycho.github.io'
    - name: Set up Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version: 21
        distribution: 'temurin'
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
      with:
        maven-version: 3.9.12
    - name: Build site-doc
      env:
       JAVA_HOME: ${{ env.JAVA_HOME_21_X64 }}
      run: | 
        mvn -U -V -e -B -ntp clean install site site:stage --file tycho/pom.xml -T1C -DskipTests
    - name: Upload site-doc
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: site-docs-${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || env.GITHUB_REF_NAME }}
        if-no-files-found: error
        path: |
          ${{ github.workspace }}/tycho/target/staging/**/*.*
    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        cd ${{ github.workspace }}/page/doc/
        git config user.name "Tycho Bot"
        git config user.email tycho-bot@eclipse.org
        cp -r ${{ github.workspace }}/tycho/target/staging/* ${{ env.GITHUB_REF_NAME }}
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -am "Update sitedocs for branch ${{ env.GITHUB_REF_NAME }}"
        git push

