name: Publish Tycho site-docs
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
on:
  push:
    branches: 
      - 'main'
permissions:
  contents: read

jobs:
  build:
    name: Publish site-docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write
      repository-projects: write
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@102b1a064a9b145e56556e22b18b19c624538d94 # v4.4.1
    - name: Checkout tycho code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
       path: 'tycho'
    - name: Checkout page
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
       path: 'page'
       token: ${{ secrets.TYCHO_SITE_PAT }}
       repository: 'eclipse-tycho/eclipse-tycho.github.io'
    - name: Set up Java
      uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Cache local Maven repository
      uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-site-${{ hashFiles('**/pom.xml', '**/*.target') }}
        restore-keys: |
          ${{ runner.os }}-maven-site-
    - name: Set up Maven
      uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
      with:
        maven-version: 3.9.6
    - name: Build site-doc
      env:
       JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
      run: | 
        mvn -U -V -e -B -ntp clean install site site:stage --file tycho/pom.xml -T1C -DskipTests
    - name: Upload site-doc
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: site-docs-${{ env.GITHUB_REF_NAME }}
        if-no-files-found: error
        path: |
          ${{ github.workspace }}/tycho/target/staging/**/*.*
    - run: |
        cd ${{ github.workspace }}/page/doc/
        git config user.name "Tycho Bot"
        git config user.email tycho-bot@eclipse.org
        cp -r ${{ github.workspace }}/tycho/target/staging/* ${{ env.GITHUB_REF_NAME }}
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -am "Update sitedocs for branch ${{ env.GITHUB_REF_NAME }}"
        git push

