name: Publish Tycho site-docs
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
on:
  push:
    branches: 
      - 'main'
permissions:
  contents: read

jobs:
  build:
    name: Publish site-docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write
      repository-projects: write
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@aba9f8db6ef36e0733227a62673d6592b1f430ea # v5.0.0
    - name: Checkout tycho code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
       path: 'tycho'
    - name: Checkout page
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
       path: 'page'
       token: ${{ secrets.TYCHO_SITE_PAT }}
       repository: 'eclipse-tycho/eclipse-tycho.github.io'
    - name: Set up Java
      uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Cache local Maven repository
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-site-${{ hashFiles('**/pom.xml', '**/*.target') }}
        restore-keys: |
          ${{ runner.os }}-maven-site-
    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
      with:
        maven-version: 3.9.9
    - name: Build site-doc
      env:
       JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
      run: | 
        mvn -U -V -e -B -ntp clean install site site:stage --file tycho/pom.xml -T1C -DskipTests
    - name: Upload site-doc
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: site-docs-${{ env.GITHUB_REF_NAME }}
        if-no-files-found: error
        path: |
          ${{ github.workspace }}/tycho/target/staging/**/*.*
    - run: |
        cd ${{ github.workspace }}/page/doc/
        git config user.name "Tycho Bot"
        git config user.email tycho-bot@eclipse.org
        cp -r ${{ github.workspace }}/tycho/target/staging/* ${{ env.GITHUB_REF_NAME }}
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -am "Update sitedocs for branch ${{ env.GITHUB_REF_NAME }}"
        git push

