# This workflow build the "Eclipse Platform Aggregator Build"
# For more information see: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/

name: Verify Eclipse Platform Aggregator Build
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
on:
  pull_request:
    branches: 
     - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tycho code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
       path: 'tycho'
    - name: Checkout platform code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
       path: 'platform'
       submodules: 'recursive'
       lfs: true
       repository: 'eclipse-platform/eclipse.platform.releng.aggregator'
       fetch-depth: 0
    - name: Set up Java
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
      with:
        java-version: |
            8
            11
            21
            17
        distribution: 'temurin'
    - name: Cache local Maven repository
      uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-verify-platform-${{ hashFiles('**/pom.xml', '**/*.target') }}
        restore-keys: |
          ${{ runner.os }}-maven-verify-platform-
    - name: Set up Maven
      uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
      with:
        maven-version: 3.9.6
    - name: Build Tycho
      env:
       JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
      working-directory: 'tycho'
      run: >- 
        mvn -U -V -e -B -ntp
        -DskipTests
        --file pom.xml
        -T1C
        --global-toolchains ${{ github.workspace }}/tycho/.github/toolchains.xml
        clean install
    - name: Run Platform Build
      env:
       JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
      working-directory: 'platform'
      run: >- 
        mvn -U -V -e -B -ntp
        --global-toolchains ${{ github.workspace }}/tycho/.github/toolchains.xml
        --file pom.xml
        --settings ${{ github.workspace }}/tycho/.github/settings.xml
        -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
        -DskipTests
        -Pbree-libs
        -Dtycho.version=5.0.0-SNAPSHOT
        clean verify
