name: Verify Eclipse Platform Aggregator Build
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
on:
  pull_request:
    branches: 
     - 'main'

jobs:
  build-aggregator:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tycho code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
       path: 'tycho'
    - name: Checkout platform code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
       path: 'aggregator'
       submodules: 'recursive'
       lfs: true
       repository: 'eclipse-platform/eclipse.platform.releng.aggregator'
       fetch-depth: 0
    - name: Set up Java
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        java-version: |
            8
            11
            17
            21
        mvn-toolchain-id: |
            JavaSE-1.8
            JavaSE-11
            JavaSE-17
            JavaSE-21
        distribution: 'temurin'
    - name: Cache local Maven repository
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-verify-platform-${{ hashFiles('**/pom.xml', '**/*.target') }}
        restore-keys: |
          ${{ runner.os }}-maven-verify-platform-
    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
      with:
        maven-version: 3.9.11
    - name: Build Tycho
      env:
       JAVA_HOME: ${{ env.JAVA_HOME_21_X64 }}
      working-directory: 'tycho'
      run: >- 
        mvn -U -V -e -B -ntp
        -DskipTests
        --file pom.xml
        -T1C
        clean install
    - name: Run Platform Build
      env:
       JAVA_HOME: ${{ env.JAVA_HOME_21_X64 }}
      working-directory: 'aggregator'
      run: >- 
        mvn -U -V -e -B -ntp
        --file pom.xml
        --settings ${{ github.workspace }}/tycho/.github/settings.xml
        -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
        -DskipTests
        -Pbree-libs
        -Dtycho.version=$(mvn help:evaluate -f ${{ github.workspace }}/tycho -Dexpression=project.version -q -DforceStdout)
        clean verify
