# This workflow build the "Eclipse Platform Aggregator Build"
# For more information see: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/

name: Verify Eclipse Platform Aggregator Build
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
on:
  pull_request:
    branches: 
     - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tycho code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      with:
       path: 'tycho'
    - name: Checkout platform code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      with:
       path: 'platform'
       submodules: 'recursive'
       lfs: true
       repository: 'eclipse-platform/eclipse.platform.releng.aggregator'
       fetch-depth: 0
    - name: Set up Java
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        java-version: |
            8
            11
            19
            17
        distribution: 'temurin'
    - name: Cache local Maven repository
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-verify-platform-${{ hashFiles('**/pom.xml', '**/*.target') }}
        restore-keys: |
          ${{ runner.os }}-maven-verify-platform-
    - name: Set up Maven
      uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
      with:
        maven-version: 3.9.2
    - name: Build Tycho
      env:
       JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
      working-directory: 'tycho'
      run: >- 
        mvn -U -V -e -B -ntp
        -DskipTests
        --file pom.xml
        -T1C
        --global-toolchains ${{ github.workspace }}/tycho/.github/toolchains.xml
        clean install
    - name: Run Platform Build
      env:
       JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
      working-directory: 'platform'
      run: >- 
        mvn -U -V -e -B -ntp
        --global-toolchains ${{ github.workspace }}/tycho/.github/toolchains.xml
        --file pom.xml
        --settings ${{ github.workspace }}/tycho/.github/settings.xml
        -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
        -DskipTests
        -Pbree-libs
        -Dtycho.version=4.0.0-SNAPSHOT
        clean verify
